// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC87jpP70jwKGJuu-8Sb19aHjTXW29NPgY',
    appId: '1:676908445904:web:eec4bcde769c2089b12ed5',
    messagingSenderId: '676908445904',
    projectId: 'drink-5f4d1',
    authDomain: 'drink-5f4d1.firebaseapp.com',
    storageBucket: 'drink-5f4d1.firebasestorage.app',
    measurementId: 'G-CW6KZN3P6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE3W5-6dQaGoPBQC2CfE4v3bqrkRylpu0',
    appId: '1:29211106170:android:5036e4a740b8cc3094d4c3',
    messagingSenderId: '29211106170',
    projectId: 'flutter-project-94d02',
    storageBucket: 'flutter-project-94d02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD3fAmtR7sszrzCs4om_9BESq6UOsA7s8',
    appId: '1:29211106170:ios:3fd2558140a8b02894d4c3',
    messagingSenderId: '29211106170',
    projectId: 'flutter-project-94d02',
    storageBucket: 'flutter-project-94d02.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnx0KQj-6yWA92qtnKAeR80zD6tS22ock',
    appId: '1:676908445904:ios:814626939fd1c922b12ed5',
    messagingSenderId: '676908445904',
    projectId: 'drink-5f4d1',
    storageBucket: 'drink-5f4d1.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC87jpP70jwKGJuu-8Sb19aHjTXW29NPgY',
    appId: '1:676908445904:web:c36e820592adfe56b12ed5',
    messagingSenderId: '676908445904',
    projectId: 'drink-5f4d1',
    authDomain: 'drink-5f4d1.firebaseapp.com',
    storageBucket: 'drink-5f4d1.firebasestorage.app',
    measurementId: 'G-LYJ78F9VJ4',
  );

}